### ISSUE TITLE
Installation from GitHub fails

### ISSUE THREAD

**Issue by CarlesCG** [jto888/FaultTree#10]
Alternatively install from this repo on GitHub: `devtools::install_github("jto888/FaultTree")` and get the following error: 

`
Error in parse(outFile) :   
/tmp/RtmpuRtF7C/devtools5977ab41e45/jto888-FaultTree-1c79166/R/test.ftree.R:18:0: unexpected end of input  
16:         }
17: }
   ^
ERROR: unable to collate and parse R files for package ‘FaultTree’
`

**Comment by CarlesCG** [comment]
**Fix**:  There was a missing { in one of the files (see commit reference above for specifics). 
Now when `devtools::install_github("CarlesCG/FaultTree")` install properly. 

@jto888 You can add the { or I can pull request to the repo.  
My guess issue #9 has a similar problem.

**Comment by jto888** [comment]
Carles,

I found it! This problem was created because I had two separate versions 
of FaultTree. One in SVN for R-Forge and one on github.

The R-Forge version has been fine all along. There are installation 
problems using the install command line that R-Forge provides - I don't 
know why this happens, but I think it is a problem at R-Forge, not the 
SVN repository. To install from R-Forge I have been downloading the .zip 
file next to the Windows logo, then installing that package from local 
files. This seems to work all the time.  The build on R-Forge would have 
failed with the  flaw that was on github but R-Forge was oblivious to a 
development snafu involving a new VOTE gate functionality.

The problem was that - out of sync -  between the two systems I had 
added a VOTEcalc.R file in addition to adding a VOTE gate functionality 
to  to several other files.  The VOTEcalc.R file was missing a closing 
bracket at line 53, but the report of failure referred to the end of 
test.ftree.R.  I don't know why failure reports come out this way, but 
this was the problem.

The master on github has now been reverted to a state before I attempted 
to add the VOTE gate.  It builds identically to the repository on 
R-Forge. I will have to recover the vote gate development activity and 
think about how badly I really want it in the midst of focus on the PRA 
model. I changed the version number to 14 to clarify for myself the 
distinction of this new synchronization.

Dave

**Comment by CarlesCG** [comment]
Perfect! Glad to hear ^^
I like the verbosity of `devtools` when trying to install from GitHub. It was a matter to look to a couple of files and trace them down at the source.  

As a side note, I avoid this kind of possible building errors using the `roxygen2` package and the framework proposed to develop packages from [R packages](http://r-pkgs.had.co.nz) by Hadley W.

**Comment by CarlesCG** [comment]
Yeap, confirm `devtools::install_github("jto888/FaultTree")` installation is succesfull
