### ISSUE TITLE
Adding nodes by pipe operator

### ISSUE THREAD

**Issue by CarlesCG** [jto888/FaultTree#6]
_Question:_
Did you consider to pipe `%` the arguments when you are expanding the fault tree? 
btw Great work!

``` r
library(FaultTree)
library(magrittr)

tree1 <- ftree.make(type="cond",repairable_cond=TRUE, name="Site power loss")
tree1 <- tree1 %>% 
 addLogic( ., at=1, type="or", name="neither emergency", name2="generator operable") %>% 
 addLogic( ., at=2, type="and", name="Independent failure", name2="of generators") %>% 
 addLatent(., at=3, mttf=5, mttr=12/8760,inspect=1/26, name="e-gen set fails") %>% 
 addLatent(., at=3, mttf=5, mttr=12/8760,inspect=1/26, name="e-gen set fails") %>% 
 addLogic( ., at=2, type="inhibit", name="Common cause", name2="failure of generators") %>% 
 addProbability(., at=6, prob=.05, name="Common cause", name2="beta factor") %>% 
 addLatent(., at=6, mttf=5,mttr=12/8760,inspect=1/26, name="e-gen set fails") %>% 
 addDemand(., at=1, mttf=1.0, name="External power", name2="interruption")

tree1 <- ftree.calc(tree1)
tree1

ftree2html(tree1, write_file=TRUE)
browseURL('tree1.html')
```

Gist [here](https://gist.github.com/CarlesCG/a8069f33237f33947622d9aea6bef74b)

**Comment by jto888** [comment]
Oh my, yes, the magrittr package cleans up the functional programming 
syntax beautifully.  Another Hadley Wickham project I note.

Well, I have to think about this. I am trying to ease the newbie into 
R.  Multiple packages can frustrate that.  I have been quite pleased to 
have the current FaultTree package completely developed off of the base 
R.  This is also why I developed FaultTree.widget separately.

Before any writing for newcomers, I was pleased that I could just pass 
them a .zip of the package by e-mail with instructions for installing in 
R.  Installation from the command line provided by R-Forge can also be 
confounded by package dependencies.  Also, the html generated by 
ftree2html uses the CDN for D3 library loading. This makes the 
visualization output very portable at the expense of requiring an active 
web connection. (As a difference, the htmlwidget stores the D3 library 
and loads it from local memory thereby containing the entire project 
locally.)

As I envision approaching a CRAN submission soon, the use of 
dependencies is less of concern since newcomers can still just request 
installation of FaultTree and the dependencies will follow.  I plan to 
release to CRAN as a widget, but still maintain ftree2html. (This risks 
the two html code sections going out of sync as they are today.) In the 
CRAN environment adding magrittr as a dependency is a no-brainer and 
demo code could just show the magrittr formatted scripts I suppose.

By the way any future for abrem as 'Weibull-R' will likely use D3 for 
rendering in the browser like this.

**Comment by CarlesCG** [comment]
I understand. There are trade offs. Still I believe the pipe operator adds interpretability while reducing code. 
It is great that the package is entirely develop with base R. Kudos.

**Comment by jto888** [comment]
It turns out that this feature was very helpful in a later "chapter" of the tutorial, so now magrittr is listed as a recommend (not dependency) in the package DESCRIPTION
